version: '3.4'

services:
  delveremote:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 18080:8080
      - 2345:2345
    privileged: true # Delveで必要なので付与します。セキュリティ面から本番環境では使うべきではありません。 
    command: dlv debug --headless --listen=:2345 --log --api-version=2 